services:
  itcm-recsys:
    container_name: itcm-recsys
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
    environment:
      PYTHONPATH: /workspace
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    mem_limit: "12g"
    shm_size: "2g"
    cpus: "6"
    command: bash -lc "sleep infinity"
